Controllers/RegisterClaimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RegisterClaim.Models;
using System.Data.SqlClient;
using System.Configuration;
using System.IO;
using System.Threading.Tasks;

namespace RegisterClaim.Controllers
{
    public class RegisterClaimController : Controller
    {
        // GET: RegisterClaim
        Hospital_MSEntities2 objlist = new Hospital_MSEntities2();
        Hospital_MSEntities3 newlist = new Hospital_MSEntities3();
        public ActionResult Index()
        {
            List<Dependent> DependentList = objlist.Dependents.ToList();
            ViewBag.dependentsTable = new SelectList(DependentList, "DependentsID", "DependentName");
            List<AllEmployee> MyEmp = objlist.AllEmployees.ToList();
            ViewBag.EmpList = new SelectList(MyEmp, "EmpID", "Employees");
            List<AllEmployee> cn = objlist.AllEmployees.ToList();
            ViewBag.NumberList = new SelectList(cn, "EmpID", "CardNumber");
            List<Disease> DiseaseList = newlist.Diseases.ToList();
            ViewBag.diseaseTable = new SelectList(DiseaseList, "id", "DiseaseName");
            List<Disease> CodeList = newlist.Diseases.ToList();
            ViewBag.codeTable = new SelectList(CodeList, "id", "DiseaseCode");
            List<Hospital> HospitalList = newlist.Hospitals.ToList();
            ViewBag.hospitalTable = new SelectList(HospitalList, "id", "HospitalName");
          
            return View();
        }

        [HttpPost]
        public ActionResult Index(RegisterClass1 rc)
        {
            string mainconn = ConfigurationManager.ConnectionStrings["myconnection"].ConnectionString;
            SqlConnection sqlconn = new SqlConnection(mainconn);
           
            string sqlquery = "insert into Claim_Register (CardNumber,EmployeeName,PatientName,HospitalName,HospitalID,ClaimCategory,DiseaseName,DiseaseCode,MedicalRecordNumber,Contact,Approval_Amount,TreatingConsultant,ExternalRemarks,InternalRemarks,CreatedDate) values (@CardNumber,@EmployeeName,@PateintName,@HospitalName,@HospitalID,@ClaimCategory,@DiseaseName,@DiseaseCode,@MedicalRecordNumber,@Contact,@Approval_Amount,@TreatingConsultant,@ExternalRemarks,@InternalRemarks,@CreatedDate);" + "insert into Files (FileName) values (@FileName)";
            SqlCommand sqlcomm = new SqlCommand(sqlquery, sqlconn);
            sqlconn.Open();
           
            sqlcomm.Parameters.AddWithValue("@CardNumber", rc.CardNumber);
            sqlcomm.Parameters.AddWithValue("@EmployeeName", rc.EmployeeName);
            sqlcomm.Parameters.AddWithValue("@PateintName", rc.PatientName);
            sqlcomm.Parameters.AddWithValue("@HospitalName", rc.HospitalName);
            sqlcomm.Parameters.AddWithValue("@HospitalID", rc.HospitalID);
            sqlcomm.Parameters.AddWithValue("@ClaimCategory", rc.ClaimCategory);
            sqlcomm.Parameters.AddWithValue("@DiseaseName", rc.DiseaseName);
            sqlcomm.Parameters.AddWithValue("@DiseaseCode", rc.DiseaseCode);
            sqlcomm.Parameters.AddWithValue("@MedicalRecordNumber", rc.MedicalRecordNumber);
            sqlcomm.Parameters.AddWithValue("@Contact", rc.Contact);
            sqlcomm.Parameters.AddWithValue("@Approval_Amount", rc.Approval_Amount);
            sqlcomm.Parameters.AddWithValue("@TreatingConsultant", rc.TreatingConsultant);
            sqlcomm.Parameters.AddWithValue("@ExternalRemarks", rc.ExternalRemarks);
            sqlcomm.Parameters.AddWithValue("@InternalRemarks", rc.InternalRemarks);
            sqlcomm.Parameters.AddWithValue("@CreatedDate", rc.CreatedDate);

            /*if (file != null && file.ContentLength > 0) {
                string filename = Path.GetFileName(file.FileName);
                string imgpath = Path.Combine(Server.MapPath("~/documents/"),filename);
                file.SaveAs(imgpath);
            }*/



            Task.Run(() => UploadFile(rc.FileName));
            
          //  Task.WaitAll();
            //return RedirectToAction("Files");


            sqlcomm.Parameters.AddWithValue("@FileName", "~/documents/" + rc.FileName);
            sqlcomm.ExecuteNonQuery();


            sqlconn.Close();
            ViewData["Message"] = "Registration Successfull";



            return View("Index");
            
        }

        public async Task<string> UploadFile(IEnumerable<HttpPostedFileBase> file)
        {

            //Console.WriteLine(file.FileName);
            /*if (file == null || file.Length == 0)
                return false;//return Content("file not selected");

            var path = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot",
                        file.FileName);

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }*/

            //foreach (HttpPostedFileBase file in files)
            //{
            //Checking file is available to save.
            var supportedTypes = new[] { ".jpg", ".jpeg", ".png",".pdf"};

           string extension = "";
            int file_length = file.Count();
           

            foreach (HttpPostedFileBase files in file)
            {
                extension = Path.GetExtension(files.FileName);


                if (supportedTypes.Contains(extension.ToLower()) && files.ContentLength <= (5 * 1024))
                       {
                            if (files != null && file_length < 6)
                            {
                                var InputFileName = DateTime.Now.ToString("yyyymmddMMss") + Path.GetFileName(files.FileName);
                                var ServerSavePath = Path.Combine(Server.MapPath("~/documents/") + InputFileName);
                                //Save file to server folder  
                                files.SaveAs(ServerSavePath);
                                //assigning file uploaded status to ViewBag for showing message to user.  
                                ViewBag.message = " files uploaded successfully.";
                            }
                            else if (files == null) { ViewBag.message = "No file Found"; }
                        }
                else { ViewBag.message = "only jpg,png and jpeg"; }
            }

          //  Task.WaitAll();
            //}
            //await Task.Yield();
            return ViewBag.message;

            

            //return RedirectToAction("Files");
        }
    }
}

Views/RegisterClaim/Index.cshtml
@model RegisterClaim.Models.RegisterClass1



@{
    ViewBag.Title = "Register Claim";
}
<link href="~/Content/Site.css" rel="stylesheet" />
<link href="~/Content/jQueryUI.css" rel="stylesheet" />


@using (Html.BeginForm("Index", "RegisterClaim", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div class="form-horizontal">
        <h4>Register Claim</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-md-6">
                @Html.LabelFor(model => model.CardNumber, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="">
                    @Html.DropDownListFor(model => model.MyEmployee.CardNumber,ViewBag.NumberList as SelectList,"--Select CardNumber--", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CardNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.EmployeeName, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="form-group">
                    @Html.DropDownListFor(model => model.MyEmployee.Employees, ViewBag.EmpList as SelectList, "--Select Employee--", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.PatientName, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="form-group">
                    @Html.DropDownListFor(model => model.MyDependents.DependentName,ViewBag.dependentsTable as SelectList, "--Select Patients--", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PatientName, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                @Html.LabelFor(model => model.DiseaseName, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="form-group">
                    @Html.DropDownListFor(model => model.AllDisease.DiseaseName,ViewBag.diseaseTable as SelectList,"--Select Disease--", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiseaseName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.DiseaseCode, htmlAttributes: new { @class = "control-label col-md-9" })
                <div class="form-group">
                    @Html.DropDownListFor(model => model.AllDisease.DiseaseCode,ViewBag.codeTable as SelectList,"--Disease Code--", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DiseaseCode, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.MedicalRecordNumber, htmlAttributes: new { @class = "control-label col-md-9" })
                <div class="form-group">
                    @Html.EditorFor(model => model.MedicalRecordNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MedicalRecordNumber, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.ClaimCategory, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="form-group">
                    @Html.Label("Maternity")
                    @Html.RadioButtonFor(model => model.ClaimCategory, "M")
                    @Html.ValidationMessageFor(model => model.ClaimCategory, "", new { @class = "text-danger" })

                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <br />
                    @Html.Label("Hospitalization")
                    @Html.RadioButtonFor(model => model.ClaimCategory, "H")
                    @Html.ValidationMessageFor(model => model.ClaimCategory, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="col-md-3">
                @Html.LabelFor(model => model.HospitalName, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="form-group">
                    @Html.DropDownListFor(model => model.AllHospitals.HospitalName,ViewBag.hospitalTable as SelectList,"--Select Hospital", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HospitalName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-md-3">
                @Html.LabelFor(model => model.HospitalID, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="form-group">
                    @Html.EditorFor(model => model.HospitalID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HospitalID, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Approval_Amount, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="form-group">
                    @Html.EditorFor(model => model.Approval_Amount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Approval_Amount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="offset-3 col-md-6">
                <br />
                @Html.LabelFor(model => model.TreatingConsultant, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="form-group">
                    @Html.Label("Yes")
                    @Html.RadioButtonFor(model => model.TreatingConsultant, "Y")
                    @Html.Label("No")
                    @Html.RadioButtonFor(model => model.TreatingConsultant, "N")
                    @Html.ValidationMessageFor(model => model.TreatingConsultant, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-6">
                @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="form-group">
                    @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="form-group">
                    @Html.TextBoxFor(model => model.FileName, "", new { @type = "file", @multiple = "multiple" })

                    @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
                    <p> @ViewBag.message</p>


                </div>
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="form-group">
                    @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    @Html.LabelFor(model => model.ExternalRemarks, htmlAttributes: new { @class = "control-label col-md-6" })
                    <div class="form-group">
                        @Html.TextAreaFor(model => model.ExternalRemarks, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ExternalRemarks, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(model => model.InternalRemarks, htmlAttributes: new { @class = "control-label col-md-6" })
                    <div class="form-group">
                        @Html.TextAreaFor(model => model.InternalRemarks, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.InternalRemarks, "", new { @class = "text-danger" })
                    </div>
                </div>


            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-6">
                        <input type="submit" value="Register" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>

        @Html.ViewData["Message"]
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="~/Scripts/jQuery.js"></script>
<script src="~/Scripts/jQueryDatePicker-1.js"></script>
<script src="~/Scripts/jQueryDatePicker-2.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script>

    $(document).ready(function () {
        $("#CreatedDate").datepicker({
            dateFormat: "dd-mm-yy",
            minDate: -6,
            maxDate: "+0M +0D"

        });
    });
</script>